// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/contract.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A message that stores user ID's mapped to their names
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserDirectory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key = id, value = name
	Users         map[int32]string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDirectory) Reset() {
	*x = UserDirectory{}
	mi := &file_proto_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDirectory) ProtoMessage() {}

func (x *UserDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDirectory.ProtoReflect.Descriptor instead.
func (*UserDirectory) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{1}
}

func (x *UserDirectory) GetUsers() map[int32]string {
	if x != nil {
		return x.Users
	}
	return nil
}

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_proto_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{2}
}

func (x *AddUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response after adding a user
type AddUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         map[int32]string       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	mi := &file_proto_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{3}
}

func (x *AddUserResponse) GetUsers() map[int32]string {
	if x != nil {
		return x.Users
	}
	return nil
}

type RemoveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	mi := &file_proto_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{5}
}

var File_proto_contract_proto protoreflect.FileDescriptor

const file_proto_contract_proto_rawDesc = "" +
	"\n" +
	"\x14proto/contract.proto\x12\bcontract\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x83\x01\n" +
	"\rUserDirectory\x128\n" +
	"\x05users\x18\x01 \x03(\v2\".contract.UserDirectory.UsersEntryR\x05users\x1a8\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x0eAddUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x87\x01\n" +
	"\x0fAddUserResponse\x12:\n" +
	"\x05users\x18\x01 \x03(\v2$.contract.AddUserResponse.UsersEntryR\x05users\x1a8\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11RemoveUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\a\n" +
	"\x05Empty2\x85\x02\n" +
	"\x14UserDirectoryService\x124\n" +
	"\aAddUser\x12\x18.contract.AddUserRequest\x1a\x0f.contract.Empty\x12:\n" +
	"\n" +
	"RemoveUser\x12\x1b.contract.RemoveUserRequest\x1a\x0f.contract.Empty\x12<\n" +
	"\x10GetUserDirectory\x12\x0f.contract.Empty\x1a\x17.contract.UserDirectory\x12=\n" +
	"\x0fStreamDirectory\x12\x0f.contract.Empty\x1a\x17.contract.UserDirectory0\x01B\x1aZ\x18grpc-go-demo/proto;protob\x06proto3"

var (
	file_proto_contract_proto_rawDescOnce sync.Once
	file_proto_contract_proto_rawDescData []byte
)

func file_proto_contract_proto_rawDescGZIP() []byte {
	file_proto_contract_proto_rawDescOnce.Do(func() {
		file_proto_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_contract_proto_rawDesc), len(file_proto_contract_proto_rawDesc)))
	})
	return file_proto_contract_proto_rawDescData
}

var file_proto_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_contract_proto_goTypes = []any{
	(*User)(nil),              // 0: contract.User
	(*UserDirectory)(nil),     // 1: contract.UserDirectory
	(*AddUserRequest)(nil),    // 2: contract.AddUserRequest
	(*AddUserResponse)(nil),   // 3: contract.AddUserResponse
	(*RemoveUserRequest)(nil), // 4: contract.RemoveUserRequest
	(*Empty)(nil),             // 5: contract.Empty
	nil,                       // 6: contract.UserDirectory.UsersEntry
	nil,                       // 7: contract.AddUserResponse.UsersEntry
}
var file_proto_contract_proto_depIdxs = []int32{
	6, // 0: contract.UserDirectory.users:type_name -> contract.UserDirectory.UsersEntry
	7, // 1: contract.AddUserResponse.users:type_name -> contract.AddUserResponse.UsersEntry
	2, // 2: contract.UserDirectoryService.AddUser:input_type -> contract.AddUserRequest
	4, // 3: contract.UserDirectoryService.RemoveUser:input_type -> contract.RemoveUserRequest
	5, // 4: contract.UserDirectoryService.GetUserDirectory:input_type -> contract.Empty
	5, // 5: contract.UserDirectoryService.StreamDirectory:input_type -> contract.Empty
	5, // 6: contract.UserDirectoryService.AddUser:output_type -> contract.Empty
	5, // 7: contract.UserDirectoryService.RemoveUser:output_type -> contract.Empty
	1, // 8: contract.UserDirectoryService.GetUserDirectory:output_type -> contract.UserDirectory
	1, // 9: contract.UserDirectoryService.StreamDirectory:output_type -> contract.UserDirectory
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_contract_proto_init() }
func file_proto_contract_proto_init() {
	if File_proto_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_contract_proto_rawDesc), len(file_proto_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_contract_proto_goTypes,
		DependencyIndexes: file_proto_contract_proto_depIdxs,
		MessageInfos:      file_proto_contract_proto_msgTypes,
	}.Build()
	File_proto_contract_proto = out.File
	file_proto_contract_proto_goTypes = nil
	file_proto_contract_proto_depIdxs = nil
}
