// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/contract.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserDirectoryService_StreamUserDirectory_FullMethodName = "/contract.UserDirectoryService/StreamUserDirectory"
)

// UserDirectoryServiceClient is the client API for UserDirectoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// client can request entire UserDirectory
// client always synchronized
type UserDirectoryServiceClient interface {
	// Stream updates to all connected clients
	StreamUserDirectory(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UserDirectory], error)
}

type userDirectoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDirectoryServiceClient(cc grpc.ClientConnInterface) UserDirectoryServiceClient {
	return &userDirectoryServiceClient{cc}
}

func (c *userDirectoryServiceClient) StreamUserDirectory(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UserDirectory], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserDirectoryService_ServiceDesc.Streams[0], UserDirectoryService_StreamUserDirectory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, UserDirectory]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserDirectoryService_StreamUserDirectoryClient = grpc.ServerStreamingClient[UserDirectory]

// UserDirectoryServiceServer is the server API for UserDirectoryService service.
// All implementations must embed UnimplementedUserDirectoryServiceServer
// for forward compatibility.
//
// client can request entire UserDirectory
// client always synchronized
type UserDirectoryServiceServer interface {
	// Stream updates to all connected clients
	StreamUserDirectory(*Empty, grpc.ServerStreamingServer[UserDirectory]) error
	mustEmbedUnimplementedUserDirectoryServiceServer()
}

// UnimplementedUserDirectoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserDirectoryServiceServer struct{}

func (UnimplementedUserDirectoryServiceServer) StreamUserDirectory(*Empty, grpc.ServerStreamingServer[UserDirectory]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUserDirectory not implemented")
}
func (UnimplementedUserDirectoryServiceServer) mustEmbedUnimplementedUserDirectoryServiceServer() {}
func (UnimplementedUserDirectoryServiceServer) testEmbeddedByValue()                              {}

// UnsafeUserDirectoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDirectoryServiceServer will
// result in compilation errors.
type UnsafeUserDirectoryServiceServer interface {
	mustEmbedUnimplementedUserDirectoryServiceServer()
}

func RegisterUserDirectoryServiceServer(s grpc.ServiceRegistrar, srv UserDirectoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserDirectoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserDirectoryService_ServiceDesc, srv)
}

func _UserDirectoryService_StreamUserDirectory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserDirectoryServiceServer).StreamUserDirectory(m, &grpc.GenericServerStream[Empty, UserDirectory]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserDirectoryService_StreamUserDirectoryServer = grpc.ServerStreamingServer[UserDirectory]

// UserDirectoryService_ServiceDesc is the grpc.ServiceDesc for UserDirectoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserDirectoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract.UserDirectoryService",
	HandlerType: (*UserDirectoryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUserDirectory",
			Handler:       _UserDirectoryService_StreamUserDirectory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/contract.proto",
}
