// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/contract.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message
type ContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractRequest) Reset() {
	*x = ContractRequest{}
	mi := &file_proto_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRequest) ProtoMessage() {}

func (x *ContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRequest.ProtoReflect.Descriptor instead.
func (*ContractRequest) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{0}
}

func (x *ContractRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message
type ContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractResponse) Reset() {
	*x = ContractResponse{}
	mi := &file_proto_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractResponse) ProtoMessage() {}

func (x *ContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractResponse.ProtoReflect.Descriptor instead.
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{1}
}

func (x *ContractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_contract_proto protoreflect.FileDescriptor

const file_proto_contract_proto_rawDesc = "" +
	"\n" +
	"\x14proto/contract.proto\x12\bcontract\"%\n" +
	"\x0fContractRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10ContractResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2T\n" +
	"\x0fContractService\x12A\n" +
	"\bSayHello\x12\x19.contract.ContractRequest\x1a\x1a.contract.ContractResponseB\x1aZ\x18grpc-go-demo/proto;protob\x06proto3"

var (
	file_proto_contract_proto_rawDescOnce sync.Once
	file_proto_contract_proto_rawDescData []byte
)

func file_proto_contract_proto_rawDescGZIP() []byte {
	file_proto_contract_proto_rawDescOnce.Do(func() {
		file_proto_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_contract_proto_rawDesc), len(file_proto_contract_proto_rawDesc)))
	})
	return file_proto_contract_proto_rawDescData
}

var file_proto_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_contract_proto_goTypes = []any{
	(*ContractRequest)(nil),  // 0: contract.ContractRequest
	(*ContractResponse)(nil), // 1: contract.ContractResponse
}
var file_proto_contract_proto_depIdxs = []int32{
	0, // 0: contract.ContractService.SayHello:input_type -> contract.ContractRequest
	1, // 1: contract.ContractService.SayHello:output_type -> contract.ContractResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_contract_proto_init() }
func file_proto_contract_proto_init() {
	if File_proto_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_contract_proto_rawDesc), len(file_proto_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_contract_proto_goTypes,
		DependencyIndexes: file_proto_contract_proto_depIdxs,
		MessageInfos:      file_proto_contract_proto_msgTypes,
	}.Build()
	File_proto_contract_proto = out.File
	file_proto_contract_proto_goTypes = nil
	file_proto_contract_proto_depIdxs = nil
}
